#!/bin/bash

# set the number of nodes and processes per node
#PBS -q qmw24 -l select=1:ncpus=24

# set name of job
#PBS -N MATLAB 
# use submission environment
#PBS -V

# start the job from the directory it was submitted
echo "start the job from the directory it was submitted"
echo "cd  $PBS_O_WORKDIR"
cd $PBS_O_WORKDIR

export INPUT=paralleldemo_parfor_bench.m   # (THIS VARIABLE MUST BE EQUAL TO YOUR MATLAB INPUT FILE !)

# input files check before submitting
if [ ! -f $PBS_O_WORKDIR/$INPUT ]; then
        echo "missing $PBS_O_WORKDIR/$INPUT  Matlab input file"
        exit 1
fi

# set some variables...
export MCRROOT=/usr/local/MATLAB/R2016a
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MCRROOT/sys/os/glnxa64:$MCRROOT/sys/java/jre/glnxa64/jre/lib/amd64/server:$MCRROOT/sys/java/jre/glnxa64/jre/lib/amd64:$MCRROOT/sys/opengl/lib/glnxa64
echo $LD_LIBRARY_PATH
echo " "
export PATH=/usr/local/MATLAB/R2016a/bin:$PATH
echo $PATH
echo " "

############################################################
#                                                          #
#    Execute the run.  Do not run in the background.       #
#                                                          #
############################################################

echo "running Matlab job in " `pwd`
echo "matlab -nodisplay -nodesktop -nosplash ... "
matlab -nodisplay -nodesktop -nosplash -r "paralleldemo_parfor_bench, exit" >& paralleldemo_parfor_bench.out

echo "Job completed"
exit

